
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.16.0
 */

package sap.example.odata.generate.namespaces.odata;

import java.math.BigDecimal;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import sap.example.odata.generate.services.OdataService;


/**
 * <p>Original entity name from the Odata EDM: <b>Alphabetical_list_of_product</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class Alphabetical_list_of_product
    extends VdmEntity<Alphabetical_list_of_product>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "NorthwindModel.Alphabetical_list_of_product";
    /**
     * Selector for all available fields of Alphabetical_list_of_product.
     * 
     */
    public final static SimpleProperty<Alphabetical_list_of_product> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductID</b></p>
     * 
     * @return
     *     The productID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ProductID")
    private Integer productID;
    public final static SimpleProperty.NumericInteger<Alphabetical_list_of_product> PRODUCT_ID = new SimpleProperty.NumericInteger<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "ProductID");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductName</b></p>
     * 
     * @return
     *     The productName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ProductName")
    private java.lang.String productName;
    public final static SimpleProperty.String<Alphabetical_list_of_product> PRODUCT_NAME = new SimpleProperty.String<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "ProductName");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>SupplierID</b></p>
     * 
     * @return
     *     The supplierID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("SupplierID")
    private Integer supplierID;
    public final static SimpleProperty.NumericInteger<Alphabetical_list_of_product> SUPPLIER_ID = new SimpleProperty.NumericInteger<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "SupplierID");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>CategoryID</b></p>
     * 
     * @return
     *     The categoryID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("CategoryID")
    private Integer categoryID;
    public final static SimpleProperty.NumericInteger<Alphabetical_list_of_product> CATEGORY_ID = new SimpleProperty.NumericInteger<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "CategoryID");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>QuantityPerUnit</b></p>
     * 
     * @return
     *     The quantityPerUnit contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("QuantityPerUnit")
    private java.lang.String quantityPerUnit;
    public final static SimpleProperty.String<Alphabetical_list_of_product> QUANTITY_PER_UNIT = new SimpleProperty.String<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "QuantityPerUnit");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>UnitPrice</b></p>
     * 
     * @return
     *     The unitPrice contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("UnitPrice")
    private BigDecimal unitPrice;
    public final static SimpleProperty.NumericDecimal<Alphabetical_list_of_product> UNIT_PRICE = new SimpleProperty.NumericDecimal<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "UnitPrice");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>UnitsInStock</b></p>
     * 
     * @return
     *     The unitsInStock contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("UnitsInStock")
    private Short unitsInStock;
    public final static SimpleProperty.NumericInteger<Alphabetical_list_of_product> UNITS_IN_STOCK = new SimpleProperty.NumericInteger<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "UnitsInStock");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>UnitsOnOrder</b></p>
     * 
     * @return
     *     The unitsOnOrder contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("UnitsOnOrder")
    private Short unitsOnOrder;
    public final static SimpleProperty.NumericInteger<Alphabetical_list_of_product> UNITS_ON_ORDER = new SimpleProperty.NumericInteger<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "UnitsOnOrder");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ReorderLevel</b></p>
     * 
     * @return
     *     The reorderLevel contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ReorderLevel")
    private Short reorderLevel;
    public final static SimpleProperty.NumericInteger<Alphabetical_list_of_product> REORDER_LEVEL = new SimpleProperty.NumericInteger<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "ReorderLevel");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Discontinued</b></p>
     * 
     * @return
     *     The discontinued contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Discontinued")
    private java.lang.Boolean discontinued;
    public final static SimpleProperty.Boolean<Alphabetical_list_of_product> DISCONTINUED = new SimpleProperty.Boolean<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "Discontinued");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>CategoryName</b></p>
     * 
     * @return
     *     The categoryName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("CategoryName")
    private java.lang.String categoryName;
    public final static SimpleProperty.String<Alphabetical_list_of_product> CATEGORY_NAME = new SimpleProperty.String<Alphabetical_list_of_product>(Alphabetical_list_of_product.class, "CategoryName");

    @Nonnull
    @Override
    public Class<Alphabetical_list_of_product> getType() {
        return Alphabetical_list_of_product.class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductID</b></p>
     * 
     * @param productID
     *     The productID to set.
     */
    public void setProductID(
        @Nullable
        final Integer productID) {
        rememberChangedField("ProductID", this.productID);
        this.productID = productID;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductName</b></p>
     * 
     * @param productName
     *     The productName to set.
     */
    public void setProductName(
        @Nullable
        final java.lang.String productName) {
        rememberChangedField("ProductName", this.productName);
        this.productName = productName;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>SupplierID</b></p>
     * 
     * @param supplierID
     *     The supplierID to set.
     */
    public void setSupplierID(
        @Nullable
        final Integer supplierID) {
        rememberChangedField("SupplierID", this.supplierID);
        this.supplierID = supplierID;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>CategoryID</b></p>
     * 
     * @param categoryID
     *     The categoryID to set.
     */
    public void setCategoryID(
        @Nullable
        final Integer categoryID) {
        rememberChangedField("CategoryID", this.categoryID);
        this.categoryID = categoryID;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>QuantityPerUnit</b></p>
     * 
     * @param quantityPerUnit
     *     The quantityPerUnit to set.
     */
    public void setQuantityPerUnit(
        @Nullable
        final java.lang.String quantityPerUnit) {
        rememberChangedField("QuantityPerUnit", this.quantityPerUnit);
        this.quantityPerUnit = quantityPerUnit;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>UnitPrice</b></p>
     * 
     * @param unitPrice
     *     The unitPrice to set.
     */
    public void setUnitPrice(
        @Nullable
        final BigDecimal unitPrice) {
        rememberChangedField("UnitPrice", this.unitPrice);
        this.unitPrice = unitPrice;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>UnitsInStock</b></p>
     * 
     * @param unitsInStock
     *     The unitsInStock to set.
     */
    public void setUnitsInStock(
        @Nullable
        final Short unitsInStock) {
        rememberChangedField("UnitsInStock", this.unitsInStock);
        this.unitsInStock = unitsInStock;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>UnitsOnOrder</b></p>
     * 
     * @param unitsOnOrder
     *     The unitsOnOrder to set.
     */
    public void setUnitsOnOrder(
        @Nullable
        final Short unitsOnOrder) {
        rememberChangedField("UnitsOnOrder", this.unitsOnOrder);
        this.unitsOnOrder = unitsOnOrder;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ReorderLevel</b></p>
     * 
     * @param reorderLevel
     *     The reorderLevel to set.
     */
    public void setReorderLevel(
        @Nullable
        final Short reorderLevel) {
        rememberChangedField("ReorderLevel", this.reorderLevel);
        this.reorderLevel = reorderLevel;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Discontinued</b></p>
     * 
     * @param discontinued
     *     The discontinued to set.
     */
    public void setDiscontinued(
        @Nullable
        final java.lang.Boolean discontinued) {
        rememberChangedField("Discontinued", this.discontinued);
        this.discontinued = discontinued;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>CategoryName</b></p>
     * 
     * @param categoryName
     *     The categoryName to set.
     */
    public void setCategoryName(
        @Nullable
        final java.lang.String categoryName) {
        rememberChangedField("CategoryName", this.categoryName);
        this.categoryName = categoryName;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "Alphabetical_list_of_products";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("ProductID", getProductID());
        entityKey.addKeyProperty("ProductName", getProductName());
        entityKey.addKeyProperty("Discontinued", getDiscontinued());
        entityKey.addKeyProperty("CategoryName", getCategoryName());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("ProductID", getProductID());
        cloudSdkValues.put("ProductName", getProductName());
        cloudSdkValues.put("SupplierID", getSupplierID());
        cloudSdkValues.put("CategoryID", getCategoryID());
        cloudSdkValues.put("QuantityPerUnit", getQuantityPerUnit());
        cloudSdkValues.put("UnitPrice", getUnitPrice());
        cloudSdkValues.put("UnitsInStock", getUnitsInStock());
        cloudSdkValues.put("UnitsOnOrder", getUnitsOnOrder());
        cloudSdkValues.put("ReorderLevel", getReorderLevel());
        cloudSdkValues.put("Discontinued", getDiscontinued());
        cloudSdkValues.put("CategoryName", getCategoryName());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("ProductID")) {
                final Object value = cloudSdkValues.remove("ProductID");
                if ((value == null)||(!value.equals(getProductID()))) {
                    setProductID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("ProductName")) {
                final Object value = cloudSdkValues.remove("ProductName");
                if ((value == null)||(!value.equals(getProductName()))) {
                    setProductName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("SupplierID")) {
                final Object value = cloudSdkValues.remove("SupplierID");
                if ((value == null)||(!value.equals(getSupplierID()))) {
                    setSupplierID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("CategoryID")) {
                final Object value = cloudSdkValues.remove("CategoryID");
                if ((value == null)||(!value.equals(getCategoryID()))) {
                    setCategoryID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("QuantityPerUnit")) {
                final Object value = cloudSdkValues.remove("QuantityPerUnit");
                if ((value == null)||(!value.equals(getQuantityPerUnit()))) {
                    setQuantityPerUnit(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("UnitPrice")) {
                final Object value = cloudSdkValues.remove("UnitPrice");
                if ((value == null)||(!value.equals(getUnitPrice()))) {
                    setUnitPrice(((BigDecimal) value));
                }
            }
            if (cloudSdkValues.containsKey("UnitsInStock")) {
                final Object value = cloudSdkValues.remove("UnitsInStock");
                if ((value == null)||(!value.equals(getUnitsInStock()))) {
                    setUnitsInStock(((Short) value));
                }
            }
            if (cloudSdkValues.containsKey("UnitsOnOrder")) {
                final Object value = cloudSdkValues.remove("UnitsOnOrder");
                if ((value == null)||(!value.equals(getUnitsOnOrder()))) {
                    setUnitsOnOrder(((Short) value));
                }
            }
            if (cloudSdkValues.containsKey("ReorderLevel")) {
                final Object value = cloudSdkValues.remove("ReorderLevel");
                if ((value == null)||(!value.equals(getReorderLevel()))) {
                    setReorderLevel(((Short) value));
                }
            }
            if (cloudSdkValues.containsKey("Discontinued")) {
                final Object value = cloudSdkValues.remove("Discontinued");
                if ((value == null)||(!value.equals(getDiscontinued()))) {
                    setDiscontinued(((java.lang.Boolean) value));
                }
            }
            if (cloudSdkValues.containsKey("CategoryName")) {
                final Object value = cloudSdkValues.remove("CategoryName");
                if ((value == null)||(!value.equals(getCategoryName()))) {
                    setCategoryName(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return OdataService.DEFAULT_SERVICE_PATH;
    }

}
