
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.16.0
 */

package sap.example.odata.generate.namespaces.odata;

import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import sap.example.odata.generate.services.OdataService;


/**
 * <p>Original entity name from the Odata EDM: <b>CustomerDemographic</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class CustomerDemographic
    extends VdmEntity<CustomerDemographic>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "NorthwindModel.CustomerDemographic";
    /**
     * Selector for all available fields of CustomerDemographic.
     * 
     */
    public final static SimpleProperty<CustomerDemographic> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>CustomerTypeID</b></p>
     * 
     * @return
     *     The customerTypeID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("CustomerTypeID")
    private java.lang.String customerTypeID;
    public final static SimpleProperty.String<CustomerDemographic> CUSTOMER_TYPE_ID = new SimpleProperty.String<CustomerDemographic>(CustomerDemographic.class, "CustomerTypeID");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>CustomerDesc</b></p>
     * 
     * @return
     *     The customerDesc contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("CustomerDesc")
    private java.lang.String customerDesc;
    public final static SimpleProperty.String<CustomerDemographic> CUSTOMER_DESC = new SimpleProperty.String<CustomerDemographic>(CustomerDemographic.class, "CustomerDesc");
    /**
     * Navigation property <b>Customers</b> for <b>CustomerDemographic</b> to multiple <b>Customer</b>.
     * 
     */
    @ElementName("Customers")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private List<Customer> toCustomers;
    /**
     * Use with available request builders to apply the <b>Customers</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<CustomerDemographic, Customer> TO_CUSTOMERS = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<CustomerDemographic, Customer>(CustomerDemographic.class, "Customers", Customer.class);

    @Nonnull
    @Override
    public Class<CustomerDemographic> getType() {
        return CustomerDemographic.class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>CustomerTypeID</b></p>
     * 
     * @param customerTypeID
     *     The customerTypeID to set.
     */
    public void setCustomerTypeID(
        @Nullable
        final java.lang.String customerTypeID) {
        rememberChangedField("CustomerTypeID", this.customerTypeID);
        this.customerTypeID = customerTypeID;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>CustomerDesc</b></p>
     * 
     * @param customerDesc
     *     The customerDesc to set.
     */
    public void setCustomerDesc(
        @Nullable
        final java.lang.String customerDesc) {
        rememberChangedField("CustomerDesc", this.customerDesc);
        this.customerDesc = customerDesc;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "CustomerDemographics";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("CustomerTypeID", getCustomerTypeID());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("CustomerTypeID", getCustomerTypeID());
        cloudSdkValues.put("CustomerDesc", getCustomerDesc());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("CustomerTypeID")) {
                final Object value = cloudSdkValues.remove("CustomerTypeID");
                if ((value == null)||(!value.equals(getCustomerTypeID()))) {
                    setCustomerTypeID(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("CustomerDesc")) {
                final Object value = cloudSdkValues.remove("CustomerDesc");
                if ((value == null)||(!value.equals(getCustomerDesc()))) {
                    setCustomerDesc(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
            if ((cloudSdkValues).containsKey("Customers")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("Customers");
                if (cloudSdkValue instanceof Iterable) {
                    if (toCustomers == null) {
                        toCustomers = Lists.newArrayList();
                    } else {
                        toCustomers = Lists.newArrayList(toCustomers);
                    }
                    int i = 0;
                    for (Object item: ((Iterable<?> ) cloudSdkValue)) {
                        if (!(item instanceof Map)) {
                            continue;
                        }
                        Customer entity;
                        if (toCustomers.size()>i) {
                            entity = toCustomers.get(i);
                        } else {
                            entity = new Customer();
                            toCustomers.add(entity);
                        }
                        i = (i + 1);
                        @SuppressWarnings("unchecked")
                        final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) item);
                        entity.fromMap(inputMap);
                    }
                }
            }
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return OdataService.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfNavigationProperties() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfNavigationProperties();
        if (toCustomers!= null) {
            (cloudSdkValues).put("Customers", toCustomers);
        }
        return cloudSdkValues;
    }

    /**
     * Retrieval of associated <b>Customer</b> entities (one to many). This corresponds to the OData navigation property <b>Customers</b>.
     * <p>
     * If the navigation property for an entity <b>CustomerDemographic</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>Customers</b> is already loaded, the result will contain the <b>Customer</b> entities. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<List<Customer>> getCustomersIfPresent() {
        return Option.of(toCustomers);
    }

    /**
     * Overwrites the list of associated <b>Customer</b> entities for the loaded navigation property <b>Customers</b>.
     * <p>
     * If the navigation property <b>Customers</b> of a queried <b>CustomerDemographic</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param cloudSdkValue
     *     List of <b>Customer</b> entities.
     */
    public void setCustomers(
        @Nonnull
        final List<Customer> cloudSdkValue) {
        if (toCustomers == null) {
            toCustomers = Lists.newArrayList();
        }
        toCustomers.clear();
        toCustomers.addAll(cloudSdkValue);
    }

    /**
     * Adds elements to the list of associated <b>Customer</b> entities. This corresponds to the OData navigation property <b>Customers</b>.
     * <p>
     * If the navigation property <b>Customers</b> of a queried <b>CustomerDemographic</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param entity
     *     Array of <b>Customer</b> entities.
     */
    public void addCustomers(Customer... entity) {
        if (toCustomers == null) {
            toCustomers = Lists.newArrayList();
        }
        toCustomers.addAll(Lists.newArrayList(entity));
    }


    /**
     * Helper class to allow for fluent creation of CustomerDemographic instances.
     * 
     */
    public final static class CustomerDemographicBuilder {

        private List<Customer> toCustomers = Lists.newArrayList();

        private CustomerDemographic.CustomerDemographicBuilder toCustomers(final List<Customer> cloudSdkValue) {
            toCustomers.addAll(cloudSdkValue);
            return this;
        }

        /**
         * Navigation property <b>Customers</b> for <b>CustomerDemographic</b> to multiple <b>Customer</b>.
         * 
         * @param cloudSdkValue
         *     The Customers to build this CustomerDemographic with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public CustomerDemographic.CustomerDemographicBuilder customers(Customer... cloudSdkValue) {
            return toCustomers(Lists.newArrayList(cloudSdkValue));
        }

    }

}
