
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.16.0
 */

package sap.example.odata.generate.namespaces.odata;

import java.math.BigDecimal;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import sap.example.odata.generate.services.OdataService;


/**
 * <p>Original entity name from the Odata EDM: <b>Order_Detail</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class Order_Detail
    extends VdmEntity<Order_Detail>
    implements VdmEntitySet
{

    @Getter
    private final String odataType = "NorthwindModel.Order_Detail";
    /**
     * Selector for all available fields of Order_Detail.
     * 
     */
    public final static SimpleProperty<Order_Detail> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>OrderID</b></p>
     * 
     * @return
     *     The orderID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("OrderID")
    private Integer orderID;
    public final static SimpleProperty.NumericInteger<Order_Detail> ORDER_ID = new SimpleProperty.NumericInteger<Order_Detail>(Order_Detail.class, "OrderID");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductID</b></p>
     * 
     * @return
     *     The productID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ProductID")
    private Integer productID;
    public final static SimpleProperty.NumericInteger<Order_Detail> PRODUCT_ID = new SimpleProperty.NumericInteger<Order_Detail>(Order_Detail.class, "ProductID");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>UnitPrice</b></p>
     * 
     * @return
     *     The unitPrice contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("UnitPrice")
    private BigDecimal unitPrice;
    public final static SimpleProperty.NumericDecimal<Order_Detail> UNIT_PRICE = new SimpleProperty.NumericDecimal<Order_Detail>(Order_Detail.class, "UnitPrice");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Quantity</b></p>
     * 
     * @return
     *     The quantity contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Quantity")
    private Short quantity;
    public final static SimpleProperty.NumericInteger<Order_Detail> QUANTITY = new SimpleProperty.NumericInteger<Order_Detail>(Order_Detail.class, "Quantity");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Discount</b></p>
     * 
     * @return
     *     The discount contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Discount")
    private Float discount;
    public final static SimpleProperty.NumericDecimal<Order_Detail> DISCOUNT = new SimpleProperty.NumericDecimal<Order_Detail>(Order_Detail.class, "Discount");
    /**
     * Navigation property <b>Order</b> for <b>Order_Detail</b> to single <b>Order</b>.
     * 
     */
    @ElementName("Order")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private Order toOrder;
    /**
     * Navigation property <b>Product</b> for <b>Order_Detail</b> to single <b>Product</b>.
     * 
     */
    @ElementName("Product")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private Product toProduct;
    /**
     * Use with available request builders to apply the <b>Order</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<Order_Detail, Order> TO_ORDER = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<Order_Detail, Order>(Order_Detail.class, "Order", Order.class);
    /**
     * Use with available request builders to apply the <b>Product</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<Order_Detail, Product> TO_PRODUCT = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<Order_Detail, Product>(Order_Detail.class, "Product", Product.class);

    @Nonnull
    @Override
    public Class<Order_Detail> getType() {
        return Order_Detail.class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>OrderID</b></p>
     * 
     * @param orderID
     *     The orderID to set.
     */
    public void setOrderID(
        @Nullable
        final Integer orderID) {
        rememberChangedField("OrderID", this.orderID);
        this.orderID = orderID;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductID</b></p>
     * 
     * @param productID
     *     The productID to set.
     */
    public void setProductID(
        @Nullable
        final Integer productID) {
        rememberChangedField("ProductID", this.productID);
        this.productID = productID;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>UnitPrice</b></p>
     * 
     * @param unitPrice
     *     The unitPrice to set.
     */
    public void setUnitPrice(
        @Nullable
        final BigDecimal unitPrice) {
        rememberChangedField("UnitPrice", this.unitPrice);
        this.unitPrice = unitPrice;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Quantity</b></p>
     * 
     * @param quantity
     *     The quantity to set.
     */
    public void setQuantity(
        @Nullable
        final Short quantity) {
        rememberChangedField("Quantity", this.quantity);
        this.quantity = quantity;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Discount</b></p>
     * 
     * @param discount
     *     The discount to set.
     */
    public void setDiscount(
        @Nullable
        final Float discount) {
        rememberChangedField("Discount", this.discount);
        this.discount = discount;
    }

    @Override
    protected String getEntityCollection() {
        return "Order_Details";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("OrderID", getOrderID());
        entityKey.addKeyProperty("ProductID", getProductID());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("OrderID", getOrderID());
        cloudSdkValues.put("ProductID", getProductID());
        cloudSdkValues.put("UnitPrice", getUnitPrice());
        cloudSdkValues.put("Quantity", getQuantity());
        cloudSdkValues.put("Discount", getDiscount());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("OrderID")) {
                final Object value = cloudSdkValues.remove("OrderID");
                if ((value == null)||(!value.equals(getOrderID()))) {
                    setOrderID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("ProductID")) {
                final Object value = cloudSdkValues.remove("ProductID");
                if ((value == null)||(!value.equals(getProductID()))) {
                    setProductID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("UnitPrice")) {
                final Object value = cloudSdkValues.remove("UnitPrice");
                if ((value == null)||(!value.equals(getUnitPrice()))) {
                    setUnitPrice(((BigDecimal) value));
                }
            }
            if (cloudSdkValues.containsKey("Quantity")) {
                final Object value = cloudSdkValues.remove("Quantity");
                if ((value == null)||(!value.equals(getQuantity()))) {
                    setQuantity(((Short) value));
                }
            }
            if (cloudSdkValues.containsKey("Discount")) {
                final Object value = cloudSdkValues.remove("Discount");
                if ((value == null)||(!value.equals(getDiscount()))) {
                    setDiscount(((Float) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
            if ((cloudSdkValues).containsKey("Order")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("Order");
                if (cloudSdkValue instanceof Map) {
                    if (toOrder == null) {
                        toOrder = new Order();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) cloudSdkValue);
                    toOrder.fromMap(inputMap);
                }
            }
            if ((cloudSdkValues).containsKey("Product")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("Product");
                if (cloudSdkValue instanceof Map) {
                    if (toProduct == null) {
                        toProduct = new Product();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) cloudSdkValue);
                    toProduct.fromMap(inputMap);
                }
            }
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected String getDefaultServicePath() {
        return OdataService.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfNavigationProperties() {
        final Map<String, Object> cloudSdkValues = super.toMapOfNavigationProperties();
        if (toOrder!= null) {
            (cloudSdkValues).put("Order", toOrder);
        }
        if (toProduct!= null) {
            (cloudSdkValues).put("Product", toProduct);
        }
        return cloudSdkValues;
    }

    /**
     * Retrieval of associated <b>Order</b> entity (one to one). This corresponds to the OData navigation property <b>Order</b>.
     * <p>
     * If the navigation property for an entity <b>Order_Detail</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>Order</b> is already loaded, the result will contain the <b>Order</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<Order> getOrderIfPresent() {
        return Option.of(toOrder);
    }

    /**
     * Overwrites the associated <b>Order</b> entity for the loaded navigation property <b>Order</b>.
     * 
     * @param cloudSdkValue
     *     New <b>Order</b> entity.
     */
    public void setOrder(final Order cloudSdkValue) {
        toOrder = cloudSdkValue;
    }

    /**
     * Retrieval of associated <b>Product</b> entity (one to one). This corresponds to the OData navigation property <b>Product</b>.
     * <p>
     * If the navigation property for an entity <b>Order_Detail</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>Product</b> is already loaded, the result will contain the <b>Product</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<Product> getProductIfPresent() {
        return Option.of(toProduct);
    }

    /**
     * Overwrites the associated <b>Product</b> entity for the loaded navigation property <b>Product</b>.
     * 
     * @param cloudSdkValue
     *     New <b>Product</b> entity.
     */
    public void setProduct(final Product cloudSdkValue) {
        toProduct = cloudSdkValue;
    }


    /**
     * Helper class to allow for fluent creation of Order_Detail instances.
     * 
     */
    public final static class Order_DetailBuilder {

        private Order toOrder;
        private Product toProduct;

        private Order_Detail.Order_DetailBuilder toOrder(final Order cloudSdkValue) {
            toOrder = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>Order</b> for <b>Order_Detail</b> to single <b>Order</b>.
         * 
         * @param cloudSdkValue
         *     The Order to build this Order_Detail with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public Order_Detail.Order_DetailBuilder order(final Order cloudSdkValue) {
            return toOrder(cloudSdkValue);
        }

        private Order_Detail.Order_DetailBuilder toProduct(final Product cloudSdkValue) {
            toProduct = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>Product</b> for <b>Order_Detail</b> to single <b>Product</b>.
         * 
         * @param cloudSdkValue
         *     The Product to build this Order_Detail with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public Order_Detail.Order_DetailBuilder product(final Product cloudSdkValue) {
            return toProduct(cloudSdkValue);
        }

    }

}
