
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.16.0
 */

package sap.example.odata.generate.namespaces.odata;

import java.math.BigDecimal;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import sap.example.odata.generate.services.OdataService;


/**
 * <p>Original entity name from the Odata EDM: <b>Order_Details_Extended</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class Order_Details_Extended
    extends VdmEntity<Order_Details_Extended>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "NorthwindModel.Order_Details_Extended";
    /**
     * Selector for all available fields of Order_Details_Extended.
     * 
     */
    public final static SimpleProperty<Order_Details_Extended> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>OrderID</b></p>
     * 
     * @return
     *     The orderID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("OrderID")
    private Integer orderID;
    public final static SimpleProperty.NumericInteger<Order_Details_Extended> ORDER_ID = new SimpleProperty.NumericInteger<Order_Details_Extended>(Order_Details_Extended.class, "OrderID");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductID</b></p>
     * 
     * @return
     *     The productID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ProductID")
    private Integer productID;
    public final static SimpleProperty.NumericInteger<Order_Details_Extended> PRODUCT_ID = new SimpleProperty.NumericInteger<Order_Details_Extended>(Order_Details_Extended.class, "ProductID");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductName</b></p>
     * 
     * @return
     *     The productName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ProductName")
    private java.lang.String productName;
    public final static SimpleProperty.String<Order_Details_Extended> PRODUCT_NAME = new SimpleProperty.String<Order_Details_Extended>(Order_Details_Extended.class, "ProductName");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>UnitPrice</b></p>
     * 
     * @return
     *     The unitPrice contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("UnitPrice")
    private BigDecimal unitPrice;
    public final static SimpleProperty.NumericDecimal<Order_Details_Extended> UNIT_PRICE = new SimpleProperty.NumericDecimal<Order_Details_Extended>(Order_Details_Extended.class, "UnitPrice");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Quantity</b></p>
     * 
     * @return
     *     The quantity contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Quantity")
    private Short quantity;
    public final static SimpleProperty.NumericInteger<Order_Details_Extended> QUANTITY = new SimpleProperty.NumericInteger<Order_Details_Extended>(Order_Details_Extended.class, "Quantity");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Discount</b></p>
     * 
     * @return
     *     The discount contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Discount")
    private Float discount;
    public final static SimpleProperty.NumericDecimal<Order_Details_Extended> DISCOUNT = new SimpleProperty.NumericDecimal<Order_Details_Extended>(Order_Details_Extended.class, "Discount");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ExtendedPrice</b></p>
     * 
     * @return
     *     The extendedPrice contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ExtendedPrice")
    private BigDecimal extendedPrice;
    public final static SimpleProperty.NumericDecimal<Order_Details_Extended> EXTENDED_PRICE = new SimpleProperty.NumericDecimal<Order_Details_Extended>(Order_Details_Extended.class, "ExtendedPrice");

    @Nonnull
    @Override
    public Class<Order_Details_Extended> getType() {
        return Order_Details_Extended.class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>OrderID</b></p>
     * 
     * @param orderID
     *     The orderID to set.
     */
    public void setOrderID(
        @Nullable
        final Integer orderID) {
        rememberChangedField("OrderID", this.orderID);
        this.orderID = orderID;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductID</b></p>
     * 
     * @param productID
     *     The productID to set.
     */
    public void setProductID(
        @Nullable
        final Integer productID) {
        rememberChangedField("ProductID", this.productID);
        this.productID = productID;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductName</b></p>
     * 
     * @param productName
     *     The productName to set.
     */
    public void setProductName(
        @Nullable
        final java.lang.String productName) {
        rememberChangedField("ProductName", this.productName);
        this.productName = productName;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>UnitPrice</b></p>
     * 
     * @param unitPrice
     *     The unitPrice to set.
     */
    public void setUnitPrice(
        @Nullable
        final BigDecimal unitPrice) {
        rememberChangedField("UnitPrice", this.unitPrice);
        this.unitPrice = unitPrice;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Quantity</b></p>
     * 
     * @param quantity
     *     The quantity to set.
     */
    public void setQuantity(
        @Nullable
        final Short quantity) {
        rememberChangedField("Quantity", this.quantity);
        this.quantity = quantity;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>Discount</b></p>
     * 
     * @param discount
     *     The discount to set.
     */
    public void setDiscount(
        @Nullable
        final Float discount) {
        rememberChangedField("Discount", this.discount);
        this.discount = discount;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ExtendedPrice</b></p>
     * 
     * @param extendedPrice
     *     The extendedPrice to set.
     */
    public void setExtendedPrice(
        @Nullable
        final BigDecimal extendedPrice) {
        rememberChangedField("ExtendedPrice", this.extendedPrice);
        this.extendedPrice = extendedPrice;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "Order_Details_Extendeds";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("OrderID", getOrderID());
        entityKey.addKeyProperty("ProductID", getProductID());
        entityKey.addKeyProperty("ProductName", getProductName());
        entityKey.addKeyProperty("UnitPrice", getUnitPrice());
        entityKey.addKeyProperty("Quantity", getQuantity());
        entityKey.addKeyProperty("Discount", getDiscount());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("OrderID", getOrderID());
        cloudSdkValues.put("ProductID", getProductID());
        cloudSdkValues.put("ProductName", getProductName());
        cloudSdkValues.put("UnitPrice", getUnitPrice());
        cloudSdkValues.put("Quantity", getQuantity());
        cloudSdkValues.put("Discount", getDiscount());
        cloudSdkValues.put("ExtendedPrice", getExtendedPrice());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("OrderID")) {
                final Object value = cloudSdkValues.remove("OrderID");
                if ((value == null)||(!value.equals(getOrderID()))) {
                    setOrderID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("ProductID")) {
                final Object value = cloudSdkValues.remove("ProductID");
                if ((value == null)||(!value.equals(getProductID()))) {
                    setProductID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("ProductName")) {
                final Object value = cloudSdkValues.remove("ProductName");
                if ((value == null)||(!value.equals(getProductName()))) {
                    setProductName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("UnitPrice")) {
                final Object value = cloudSdkValues.remove("UnitPrice");
                if ((value == null)||(!value.equals(getUnitPrice()))) {
                    setUnitPrice(((BigDecimal) value));
                }
            }
            if (cloudSdkValues.containsKey("Quantity")) {
                final Object value = cloudSdkValues.remove("Quantity");
                if ((value == null)||(!value.equals(getQuantity()))) {
                    setQuantity(((Short) value));
                }
            }
            if (cloudSdkValues.containsKey("Discount")) {
                final Object value = cloudSdkValues.remove("Discount");
                if ((value == null)||(!value.equals(getDiscount()))) {
                    setDiscount(((Float) value));
                }
            }
            if (cloudSdkValues.containsKey("ExtendedPrice")) {
                final Object value = cloudSdkValues.remove("ExtendedPrice");
                if ((value == null)||(!value.equals(getExtendedPrice()))) {
                    setExtendedPrice(((BigDecimal) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return OdataService.DEFAULT_SERVICE_PATH;
    }

}
