
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.16.0
 */

package sap.example.odata.generate.namespaces.odata;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import sap.example.odata.generate.services.OdataService;


/**
 * <p>Original entity name from the Odata EDM: <b>Orders_Qry</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class Orders_Qry
    extends VdmEntity<Orders_Qry>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "NorthwindModel.Orders_Qry";
    /**
     * Selector for all available fields of Orders_Qry.
     * 
     */
    public final static SimpleProperty<Orders_Qry> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>OrderID</b></p>
     * 
     * @return
     *     The orderID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("OrderID")
    private Integer orderID;
    public final static SimpleProperty.NumericInteger<Orders_Qry> ORDER_ID = new SimpleProperty.NumericInteger<Orders_Qry>(Orders_Qry.class, "OrderID");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>CustomerID</b></p>
     * 
     * @return
     *     The customerID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("CustomerID")
    private java.lang.String customerID;
    public final static SimpleProperty.String<Orders_Qry> CUSTOMER_ID = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "CustomerID");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>EmployeeID</b></p>
     * 
     * @return
     *     The employeeID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("EmployeeID")
    private Integer employeeID;
    public final static SimpleProperty.NumericInteger<Orders_Qry> EMPLOYEE_ID = new SimpleProperty.NumericInteger<Orders_Qry>(Orders_Qry.class, "EmployeeID");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>OrderDate</b></p>
     * 
     * @return
     *     The orderDate contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("OrderDate")
    private OffsetDateTime orderDate;
    public final static SimpleProperty.DateTime<Orders_Qry> ORDER_DATE = new SimpleProperty.DateTime<Orders_Qry>(Orders_Qry.class, "OrderDate");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>RequiredDate</b></p>
     * 
     * @return
     *     The requiredDate contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("RequiredDate")
    private OffsetDateTime requiredDate;
    public final static SimpleProperty.DateTime<Orders_Qry> REQUIRED_DATE = new SimpleProperty.DateTime<Orders_Qry>(Orders_Qry.class, "RequiredDate");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShippedDate</b></p>
     * 
     * @return
     *     The shippedDate contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ShippedDate")
    private OffsetDateTime shippedDate;
    public final static SimpleProperty.DateTime<Orders_Qry> SHIPPED_DATE = new SimpleProperty.DateTime<Orders_Qry>(Orders_Qry.class, "ShippedDate");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipVia</b></p>
     * 
     * @return
     *     The shipVia contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ShipVia")
    private Integer shipVia;
    public final static SimpleProperty.NumericInteger<Orders_Qry> SHIP_VIA = new SimpleProperty.NumericInteger<Orders_Qry>(Orders_Qry.class, "ShipVia");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Freight</b></p>
     * 
     * @return
     *     The freight contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Freight")
    private BigDecimal freight;
    public final static SimpleProperty.NumericDecimal<Orders_Qry> FREIGHT = new SimpleProperty.NumericDecimal<Orders_Qry>(Orders_Qry.class, "Freight");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipName</b></p>
     * 
     * @return
     *     The shipName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ShipName")
    private java.lang.String shipName;
    public final static SimpleProperty.String<Orders_Qry> SHIP_NAME = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "ShipName");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipAddress</b></p>
     * 
     * @return
     *     The shipAddress contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ShipAddress")
    private java.lang.String shipAddress;
    public final static SimpleProperty.String<Orders_Qry> SHIP_ADDRESS = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "ShipAddress");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipCity</b></p>
     * 
     * @return
     *     The shipCity contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ShipCity")
    private java.lang.String shipCity;
    public final static SimpleProperty.String<Orders_Qry> SHIP_CITY = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "ShipCity");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipRegion</b></p>
     * 
     * @return
     *     The shipRegion contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ShipRegion")
    private java.lang.String shipRegion;
    public final static SimpleProperty.String<Orders_Qry> SHIP_REGION = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "ShipRegion");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipPostalCode</b></p>
     * 
     * @return
     *     The shipPostalCode contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ShipPostalCode")
    private java.lang.String shipPostalCode;
    public final static SimpleProperty.String<Orders_Qry> SHIP_POSTAL_CODE = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "ShipPostalCode");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipCountry</b></p>
     * 
     * @return
     *     The shipCountry contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ShipCountry")
    private java.lang.String shipCountry;
    public final static SimpleProperty.String<Orders_Qry> SHIP_COUNTRY = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "ShipCountry");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>CompanyName</b></p>
     * 
     * @return
     *     The companyName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("CompanyName")
    private java.lang.String companyName;
    public final static SimpleProperty.String<Orders_Qry> COMPANY_NAME = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "CompanyName");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Address</b></p>
     * 
     * @return
     *     The address contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Address")
    private java.lang.String address;
    public final static SimpleProperty.String<Orders_Qry> ADDRESS = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "Address");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>City</b></p>
     * 
     * @return
     *     The city contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("City")
    private java.lang.String city;
    public final static SimpleProperty.String<Orders_Qry> CITY = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "City");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Region</b></p>
     * 
     * @return
     *     The region contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Region")
    private java.lang.String region;
    public final static SimpleProperty.String<Orders_Qry> REGION = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "Region");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>PostalCode</b></p>
     * 
     * @return
     *     The postalCode contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("PostalCode")
    private java.lang.String postalCode;
    public final static SimpleProperty.String<Orders_Qry> POSTAL_CODE = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "PostalCode");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Country</b></p>
     * 
     * @return
     *     The country contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Country")
    private java.lang.String country;
    public final static SimpleProperty.String<Orders_Qry> COUNTRY = new SimpleProperty.String<Orders_Qry>(Orders_Qry.class, "Country");

    @Nonnull
    @Override
    public Class<Orders_Qry> getType() {
        return Orders_Qry.class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>OrderID</b></p>
     * 
     * @param orderID
     *     The orderID to set.
     */
    public void setOrderID(
        @Nullable
        final Integer orderID) {
        rememberChangedField("OrderID", this.orderID);
        this.orderID = orderID;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>CustomerID</b></p>
     * 
     * @param customerID
     *     The customerID to set.
     */
    public void setCustomerID(
        @Nullable
        final java.lang.String customerID) {
        rememberChangedField("CustomerID", this.customerID);
        this.customerID = customerID;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>EmployeeID</b></p>
     * 
     * @param employeeID
     *     The employeeID to set.
     */
    public void setEmployeeID(
        @Nullable
        final Integer employeeID) {
        rememberChangedField("EmployeeID", this.employeeID);
        this.employeeID = employeeID;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>OrderDate</b></p>
     * 
     * @param orderDate
     *     The orderDate to set.
     */
    public void setOrderDate(
        @Nullable
        final OffsetDateTime orderDate) {
        rememberChangedField("OrderDate", this.orderDate);
        this.orderDate = orderDate;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>RequiredDate</b></p>
     * 
     * @param requiredDate
     *     The requiredDate to set.
     */
    public void setRequiredDate(
        @Nullable
        final OffsetDateTime requiredDate) {
        rememberChangedField("RequiredDate", this.requiredDate);
        this.requiredDate = requiredDate;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShippedDate</b></p>
     * 
     * @param shippedDate
     *     The shippedDate to set.
     */
    public void setShippedDate(
        @Nullable
        final OffsetDateTime shippedDate) {
        rememberChangedField("ShippedDate", this.shippedDate);
        this.shippedDate = shippedDate;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipVia</b></p>
     * 
     * @param shipVia
     *     The shipVia to set.
     */
    public void setShipVia(
        @Nullable
        final Integer shipVia) {
        rememberChangedField("ShipVia", this.shipVia);
        this.shipVia = shipVia;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Freight</b></p>
     * 
     * @param freight
     *     The freight to set.
     */
    public void setFreight(
        @Nullable
        final BigDecimal freight) {
        rememberChangedField("Freight", this.freight);
        this.freight = freight;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipName</b></p>
     * 
     * @param shipName
     *     The shipName to set.
     */
    public void setShipName(
        @Nullable
        final java.lang.String shipName) {
        rememberChangedField("ShipName", this.shipName);
        this.shipName = shipName;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipAddress</b></p>
     * 
     * @param shipAddress
     *     The shipAddress to set.
     */
    public void setShipAddress(
        @Nullable
        final java.lang.String shipAddress) {
        rememberChangedField("ShipAddress", this.shipAddress);
        this.shipAddress = shipAddress;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipCity</b></p>
     * 
     * @param shipCity
     *     The shipCity to set.
     */
    public void setShipCity(
        @Nullable
        final java.lang.String shipCity) {
        rememberChangedField("ShipCity", this.shipCity);
        this.shipCity = shipCity;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipRegion</b></p>
     * 
     * @param shipRegion
     *     The shipRegion to set.
     */
    public void setShipRegion(
        @Nullable
        final java.lang.String shipRegion) {
        rememberChangedField("ShipRegion", this.shipRegion);
        this.shipRegion = shipRegion;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipPostalCode</b></p>
     * 
     * @param shipPostalCode
     *     The shipPostalCode to set.
     */
    public void setShipPostalCode(
        @Nullable
        final java.lang.String shipPostalCode) {
        rememberChangedField("ShipPostalCode", this.shipPostalCode);
        this.shipPostalCode = shipPostalCode;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ShipCountry</b></p>
     * 
     * @param shipCountry
     *     The shipCountry to set.
     */
    public void setShipCountry(
        @Nullable
        final java.lang.String shipCountry) {
        rememberChangedField("ShipCountry", this.shipCountry);
        this.shipCountry = shipCountry;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>CompanyName</b></p>
     * 
     * @param companyName
     *     The companyName to set.
     */
    public void setCompanyName(
        @Nullable
        final java.lang.String companyName) {
        rememberChangedField("CompanyName", this.companyName);
        this.companyName = companyName;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Address</b></p>
     * 
     * @param address
     *     The address to set.
     */
    public void setAddress(
        @Nullable
        final java.lang.String address) {
        rememberChangedField("Address", this.address);
        this.address = address;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>City</b></p>
     * 
     * @param city
     *     The city to set.
     */
    public void setCity(
        @Nullable
        final java.lang.String city) {
        rememberChangedField("City", this.city);
        this.city = city;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Region</b></p>
     * 
     * @param region
     *     The region to set.
     */
    public void setRegion(
        @Nullable
        final java.lang.String region) {
        rememberChangedField("Region", this.region);
        this.region = region;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>PostalCode</b></p>
     * 
     * @param postalCode
     *     The postalCode to set.
     */
    public void setPostalCode(
        @Nullable
        final java.lang.String postalCode) {
        rememberChangedField("PostalCode", this.postalCode);
        this.postalCode = postalCode;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Country</b></p>
     * 
     * @param country
     *     The country to set.
     */
    public void setCountry(
        @Nullable
        final java.lang.String country) {
        rememberChangedField("Country", this.country);
        this.country = country;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "Orders_Qries";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("OrderID", getOrderID());
        entityKey.addKeyProperty("CompanyName", getCompanyName());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("OrderID", getOrderID());
        cloudSdkValues.put("CustomerID", getCustomerID());
        cloudSdkValues.put("EmployeeID", getEmployeeID());
        cloudSdkValues.put("OrderDate", getOrderDate());
        cloudSdkValues.put("RequiredDate", getRequiredDate());
        cloudSdkValues.put("ShippedDate", getShippedDate());
        cloudSdkValues.put("ShipVia", getShipVia());
        cloudSdkValues.put("Freight", getFreight());
        cloudSdkValues.put("ShipName", getShipName());
        cloudSdkValues.put("ShipAddress", getShipAddress());
        cloudSdkValues.put("ShipCity", getShipCity());
        cloudSdkValues.put("ShipRegion", getShipRegion());
        cloudSdkValues.put("ShipPostalCode", getShipPostalCode());
        cloudSdkValues.put("ShipCountry", getShipCountry());
        cloudSdkValues.put("CompanyName", getCompanyName());
        cloudSdkValues.put("Address", getAddress());
        cloudSdkValues.put("City", getCity());
        cloudSdkValues.put("Region", getRegion());
        cloudSdkValues.put("PostalCode", getPostalCode());
        cloudSdkValues.put("Country", getCountry());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("OrderID")) {
                final Object value = cloudSdkValues.remove("OrderID");
                if ((value == null)||(!value.equals(getOrderID()))) {
                    setOrderID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("CustomerID")) {
                final Object value = cloudSdkValues.remove("CustomerID");
                if ((value == null)||(!value.equals(getCustomerID()))) {
                    setCustomerID(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("EmployeeID")) {
                final Object value = cloudSdkValues.remove("EmployeeID");
                if ((value == null)||(!value.equals(getEmployeeID()))) {
                    setEmployeeID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("OrderDate")) {
                final Object value = cloudSdkValues.remove("OrderDate");
                if ((value == null)||(!value.equals(getOrderDate()))) {
                    setOrderDate(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("RequiredDate")) {
                final Object value = cloudSdkValues.remove("RequiredDate");
                if ((value == null)||(!value.equals(getRequiredDate()))) {
                    setRequiredDate(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("ShippedDate")) {
                final Object value = cloudSdkValues.remove("ShippedDate");
                if ((value == null)||(!value.equals(getShippedDate()))) {
                    setShippedDate(((OffsetDateTime) value));
                }
            }
            if (cloudSdkValues.containsKey("ShipVia")) {
                final Object value = cloudSdkValues.remove("ShipVia");
                if ((value == null)||(!value.equals(getShipVia()))) {
                    setShipVia(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("Freight")) {
                final Object value = cloudSdkValues.remove("Freight");
                if ((value == null)||(!value.equals(getFreight()))) {
                    setFreight(((BigDecimal) value));
                }
            }
            if (cloudSdkValues.containsKey("ShipName")) {
                final Object value = cloudSdkValues.remove("ShipName");
                if ((value == null)||(!value.equals(getShipName()))) {
                    setShipName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ShipAddress")) {
                final Object value = cloudSdkValues.remove("ShipAddress");
                if ((value == null)||(!value.equals(getShipAddress()))) {
                    setShipAddress(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ShipCity")) {
                final Object value = cloudSdkValues.remove("ShipCity");
                if ((value == null)||(!value.equals(getShipCity()))) {
                    setShipCity(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ShipRegion")) {
                final Object value = cloudSdkValues.remove("ShipRegion");
                if ((value == null)||(!value.equals(getShipRegion()))) {
                    setShipRegion(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ShipPostalCode")) {
                final Object value = cloudSdkValues.remove("ShipPostalCode");
                if ((value == null)||(!value.equals(getShipPostalCode()))) {
                    setShipPostalCode(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ShipCountry")) {
                final Object value = cloudSdkValues.remove("ShipCountry");
                if ((value == null)||(!value.equals(getShipCountry()))) {
                    setShipCountry(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("CompanyName")) {
                final Object value = cloudSdkValues.remove("CompanyName");
                if ((value == null)||(!value.equals(getCompanyName()))) {
                    setCompanyName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Address")) {
                final Object value = cloudSdkValues.remove("Address");
                if ((value == null)||(!value.equals(getAddress()))) {
                    setAddress(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("City")) {
                final Object value = cloudSdkValues.remove("City");
                if ((value == null)||(!value.equals(getCity()))) {
                    setCity(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Region")) {
                final Object value = cloudSdkValues.remove("Region");
                if ((value == null)||(!value.equals(getRegion()))) {
                    setRegion(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("PostalCode")) {
                final Object value = cloudSdkValues.remove("PostalCode");
                if ((value == null)||(!value.equals(getPostalCode()))) {
                    setPostalCode(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Country")) {
                final Object value = cloudSdkValues.remove("Country");
                if ((value == null)||(!value.equals(getCountry()))) {
                    setCountry(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return OdataService.DEFAULT_SERVICE_PATH;
    }

}
