
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.16.0
 */

package sap.example.odata.generate.namespaces.odata;

import java.math.BigDecimal;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import sap.example.odata.generate.services.OdataService;


/**
 * <p>Original entity name from the Odata EDM: <b>Products_Above_Average_Price</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class Products_Above_Average_Price
    extends VdmEntity<Products_Above_Average_Price>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "NorthwindModel.Products_Above_Average_Price";
    /**
     * Selector for all available fields of Products_Above_Average_Price.
     * 
     */
    public final static SimpleProperty<Products_Above_Average_Price> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductName</b></p>
     * 
     * @return
     *     The productName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ProductName")
    private java.lang.String productName;
    public final static SimpleProperty.String<Products_Above_Average_Price> PRODUCT_NAME = new SimpleProperty.String<Products_Above_Average_Price>(Products_Above_Average_Price.class, "ProductName");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>UnitPrice</b></p>
     * 
     * @return
     *     The unitPrice contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("UnitPrice")
    private BigDecimal unitPrice;
    public final static SimpleProperty.NumericDecimal<Products_Above_Average_Price> UNIT_PRICE = new SimpleProperty.NumericDecimal<Products_Above_Average_Price>(Products_Above_Average_Price.class, "UnitPrice");

    @Nonnull
    @Override
    public Class<Products_Above_Average_Price> getType() {
        return Products_Above_Average_Price.class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductName</b></p>
     * 
     * @param productName
     *     The productName to set.
     */
    public void setProductName(
        @Nullable
        final java.lang.String productName) {
        rememberChangedField("ProductName", this.productName);
        this.productName = productName;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>UnitPrice</b></p>
     * 
     * @param unitPrice
     *     The unitPrice to set.
     */
    public void setUnitPrice(
        @Nullable
        final BigDecimal unitPrice) {
        rememberChangedField("UnitPrice", this.unitPrice);
        this.unitPrice = unitPrice;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "Products_Above_Average_Prices";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("ProductName", getProductName());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("ProductName", getProductName());
        cloudSdkValues.put("UnitPrice", getUnitPrice());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("ProductName")) {
                final Object value = cloudSdkValues.remove("ProductName");
                if ((value == null)||(!value.equals(getProductName()))) {
                    setProductName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("UnitPrice")) {
                final Object value = cloudSdkValues.remove("UnitPrice");
                if ((value == null)||(!value.equals(getUnitPrice()))) {
                    setUnitPrice(((BigDecimal) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return OdataService.DEFAULT_SERVICE_PATH;
    }

}
