
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.16.0
 */

package sap.example.odata.generate.namespaces.odata;

import java.math.BigDecimal;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import sap.example.odata.generate.services.OdataService;


/**
 * <p>Original entity name from the Odata EDM: <b>Product_Sales_for_1997</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class Product_Sales_for_1997
    extends VdmEntity<Product_Sales_for_1997>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "NorthwindModel.Product_Sales_for_1997";
    /**
     * Selector for all available fields of Product_Sales_for_1997.
     * 
     */
    public final static SimpleProperty<Product_Sales_for_1997> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>CategoryName</b></p>
     * 
     * @return
     *     The categoryName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("CategoryName")
    private java.lang.String categoryName;
    public final static SimpleProperty.String<Product_Sales_for_1997> CATEGORY_NAME = new SimpleProperty.String<Product_Sales_for_1997>(Product_Sales_for_1997 .class, "CategoryName");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductName</b></p>
     * 
     * @return
     *     The productName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ProductName")
    private java.lang.String productName;
    public final static SimpleProperty.String<Product_Sales_for_1997> PRODUCT_NAME = new SimpleProperty.String<Product_Sales_for_1997>(Product_Sales_for_1997 .class, "ProductName");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ProductSales</b></p>
     * 
     * @return
     *     The productSales contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ProductSales")
    private BigDecimal productSales;
    public final static SimpleProperty.NumericDecimal<Product_Sales_for_1997> PRODUCT_SALES = new SimpleProperty.NumericDecimal<Product_Sales_for_1997>(Product_Sales_for_1997 .class, "ProductSales");

    @Nonnull
    @Override
    public Class<Product_Sales_for_1997> getType() {
        return Product_Sales_for_1997 .class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>CategoryName</b></p>
     * 
     * @param categoryName
     *     The categoryName to set.
     */
    public void setCategoryName(
        @Nullable
        final java.lang.String categoryName) {
        rememberChangedField("CategoryName", this.categoryName);
        this.categoryName = categoryName;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ProductName</b></p>
     * 
     * @param productName
     *     The productName to set.
     */
    public void setProductName(
        @Nullable
        final java.lang.String productName) {
        rememberChangedField("ProductName", this.productName);
        this.productName = productName;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ProductSales</b></p>
     * 
     * @param productSales
     *     The productSales to set.
     */
    public void setProductSales(
        @Nullable
        final BigDecimal productSales) {
        rememberChangedField("ProductSales", this.productSales);
        this.productSales = productSales;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "Product_Sales_for_1997";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("CategoryName", getCategoryName());
        entityKey.addKeyProperty("ProductName", getProductName());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("CategoryName", getCategoryName());
        cloudSdkValues.put("ProductName", getProductName());
        cloudSdkValues.put("ProductSales", getProductSales());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("CategoryName")) {
                final Object value = cloudSdkValues.remove("CategoryName");
                if ((value == null)||(!value.equals(getCategoryName()))) {
                    setCategoryName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ProductName")) {
                final Object value = cloudSdkValues.remove("ProductName");
                if ((value == null)||(!value.equals(getProductName()))) {
                    setProductName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ProductSales")) {
                final Object value = cloudSdkValues.remove("ProductSales");
                if ((value == null)||(!value.equals(getProductSales()))) {
                    setProductSales(((BigDecimal) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return OdataService.DEFAULT_SERVICE_PATH;
    }

}
