
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.16.0
 */

package sap.example.odata.generate.namespaces.odata;

import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import sap.example.odata.generate.services.OdataService;


/**
 * <p>Original entity name from the Odata EDM: <b>Shipper</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class Shipper
    extends VdmEntity<Shipper>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "NorthwindModel.Shipper";
    /**
     * Selector for all available fields of Shipper.
     * 
     */
    public final static SimpleProperty<Shipper> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ShipperID</b></p>
     * 
     * @return
     *     The shipperID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ShipperID")
    private Integer shipperID;
    public final static SimpleProperty.NumericInteger<Shipper> SHIPPER_ID = new SimpleProperty.NumericInteger<Shipper>(Shipper.class, "ShipperID");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>CompanyName</b></p>
     * 
     * @return
     *     The companyName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("CompanyName")
    private java.lang.String companyName;
    public final static SimpleProperty.String<Shipper> COMPANY_NAME = new SimpleProperty.String<Shipper>(Shipper.class, "CompanyName");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Phone</b></p>
     * 
     * @return
     *     The phone contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Phone")
    private java.lang.String phone;
    public final static SimpleProperty.String<Shipper> PHONE = new SimpleProperty.String<Shipper>(Shipper.class, "Phone");
    /**
     * Navigation property <b>Orders</b> for <b>Shipper</b> to multiple <b>Order</b>.
     * 
     */
    @ElementName("Orders")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private List<Order> toOrders;
    /**
     * Use with available request builders to apply the <b>Orders</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<Shipper, Order> TO_ORDERS = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<Shipper, Order>(Shipper.class, "Orders", Order.class);

    @Nonnull
    @Override
    public Class<Shipper> getType() {
        return Shipper.class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ShipperID</b></p>
     * 
     * @param shipperID
     *     The shipperID to set.
     */
    public void setShipperID(
        @Nullable
        final Integer shipperID) {
        rememberChangedField("ShipperID", this.shipperID);
        this.shipperID = shipperID;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>CompanyName</b></p>
     * 
     * @param companyName
     *     The companyName to set.
     */
    public void setCompanyName(
        @Nullable
        final java.lang.String companyName) {
        rememberChangedField("CompanyName", this.companyName);
        this.companyName = companyName;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Phone</b></p>
     * 
     * @param phone
     *     The phone to set.
     */
    public void setPhone(
        @Nullable
        final java.lang.String phone) {
        rememberChangedField("Phone", this.phone);
        this.phone = phone;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "Shippers";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("ShipperID", getShipperID());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("ShipperID", getShipperID());
        cloudSdkValues.put("CompanyName", getCompanyName());
        cloudSdkValues.put("Phone", getPhone());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("ShipperID")) {
                final Object value = cloudSdkValues.remove("ShipperID");
                if ((value == null)||(!value.equals(getShipperID()))) {
                    setShipperID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("CompanyName")) {
                final Object value = cloudSdkValues.remove("CompanyName");
                if ((value == null)||(!value.equals(getCompanyName()))) {
                    setCompanyName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Phone")) {
                final Object value = cloudSdkValues.remove("Phone");
                if ((value == null)||(!value.equals(getPhone()))) {
                    setPhone(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
            if ((cloudSdkValues).containsKey("Orders")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("Orders");
                if (cloudSdkValue instanceof Iterable) {
                    if (toOrders == null) {
                        toOrders = Lists.newArrayList();
                    } else {
                        toOrders = Lists.newArrayList(toOrders);
                    }
                    int i = 0;
                    for (Object item: ((Iterable<?> ) cloudSdkValue)) {
                        if (!(item instanceof Map)) {
                            continue;
                        }
                        Order entity;
                        if (toOrders.size()>i) {
                            entity = toOrders.get(i);
                        } else {
                            entity = new Order();
                            toOrders.add(entity);
                        }
                        i = (i + 1);
                        @SuppressWarnings("unchecked")
                        final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) item);
                        entity.fromMap(inputMap);
                    }
                }
            }
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return OdataService.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfNavigationProperties() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfNavigationProperties();
        if (toOrders!= null) {
            (cloudSdkValues).put("Orders", toOrders);
        }
        return cloudSdkValues;
    }

    /**
     * Retrieval of associated <b>Order</b> entities (one to many). This corresponds to the OData navigation property <b>Orders</b>.
     * <p>
     * If the navigation property for an entity <b>Shipper</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>Orders</b> is already loaded, the result will contain the <b>Order</b> entities. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<List<Order>> getOrdersIfPresent() {
        return Option.of(toOrders);
    }

    /**
     * Overwrites the list of associated <b>Order</b> entities for the loaded navigation property <b>Orders</b>.
     * <p>
     * If the navigation property <b>Orders</b> of a queried <b>Shipper</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param cloudSdkValue
     *     List of <b>Order</b> entities.
     */
    public void setOrders(
        @Nonnull
        final List<Order> cloudSdkValue) {
        if (toOrders == null) {
            toOrders = Lists.newArrayList();
        }
        toOrders.clear();
        toOrders.addAll(cloudSdkValue);
    }

    /**
     * Adds elements to the list of associated <b>Order</b> entities. This corresponds to the OData navigation property <b>Orders</b>.
     * <p>
     * If the navigation property <b>Orders</b> of a queried <b>Shipper</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param entity
     *     Array of <b>Order</b> entities.
     */
    public void addOrders(Order... entity) {
        if (toOrders == null) {
            toOrders = Lists.newArrayList();
        }
        toOrders.addAll(Lists.newArrayList(entity));
    }


    /**
     * Helper class to allow for fluent creation of Shipper instances.
     * 
     */
    public final static class ShipperBuilder {

        private List<Order> toOrders = Lists.newArrayList();

        private Shipper.ShipperBuilder toOrders(final List<Order> cloudSdkValue) {
            toOrders.addAll(cloudSdkValue);
            return this;
        }

        /**
         * Navigation property <b>Orders</b> for <b>Shipper</b> to multiple <b>Order</b>.
         * 
         * @param cloudSdkValue
         *     The Orders to build this Shipper with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public Shipper.ShipperBuilder orders(Order... cloudSdkValue) {
            return toOrders(Lists.newArrayList(cloudSdkValue));
        }

    }

}
