
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.16.0
 */

package sap.example.odata.generate.namespaces.odata;

import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import sap.example.odata.generate.services.OdataService;


/**
 * <p>Original entity name from the Odata EDM: <b>Supplier</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class Supplier
    extends VdmEntity<Supplier>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "NorthwindModel.Supplier";
    /**
     * Selector for all available fields of Supplier.
     * 
     */
    public final static SimpleProperty<Supplier> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>SupplierID</b></p>
     * 
     * @return
     *     The supplierID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("SupplierID")
    private Integer supplierID;
    public final static SimpleProperty.NumericInteger<Supplier> SUPPLIER_ID = new SimpleProperty.NumericInteger<Supplier>(Supplier.class, "SupplierID");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>CompanyName</b></p>
     * 
     * @return
     *     The companyName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("CompanyName")
    private java.lang.String companyName;
    public final static SimpleProperty.String<Supplier> COMPANY_NAME = new SimpleProperty.String<Supplier>(Supplier.class, "CompanyName");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ContactName</b></p>
     * 
     * @return
     *     The contactName contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ContactName")
    private java.lang.String contactName;
    public final static SimpleProperty.String<Supplier> CONTACT_NAME = new SimpleProperty.String<Supplier>(Supplier.class, "ContactName");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ContactTitle</b></p>
     * 
     * @return
     *     The contactTitle contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("ContactTitle")
    private java.lang.String contactTitle;
    public final static SimpleProperty.String<Supplier> CONTACT_TITLE = new SimpleProperty.String<Supplier>(Supplier.class, "ContactTitle");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Address</b></p>
     * 
     * @return
     *     The address contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Address")
    private java.lang.String address;
    public final static SimpleProperty.String<Supplier> ADDRESS = new SimpleProperty.String<Supplier>(Supplier.class, "Address");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>City</b></p>
     * 
     * @return
     *     The city contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("City")
    private java.lang.String city;
    public final static SimpleProperty.String<Supplier> CITY = new SimpleProperty.String<Supplier>(Supplier.class, "City");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Region</b></p>
     * 
     * @return
     *     The region contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Region")
    private java.lang.String region;
    public final static SimpleProperty.String<Supplier> REGION = new SimpleProperty.String<Supplier>(Supplier.class, "Region");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>PostalCode</b></p>
     * 
     * @return
     *     The postalCode contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("PostalCode")
    private java.lang.String postalCode;
    public final static SimpleProperty.String<Supplier> POSTAL_CODE = new SimpleProperty.String<Supplier>(Supplier.class, "PostalCode");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Country</b></p>
     * 
     * @return
     *     The country contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Country")
    private java.lang.String country;
    public final static SimpleProperty.String<Supplier> COUNTRY = new SimpleProperty.String<Supplier>(Supplier.class, "Country");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Phone</b></p>
     * 
     * @return
     *     The phone contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Phone")
    private java.lang.String phone;
    public final static SimpleProperty.String<Supplier> PHONE = new SimpleProperty.String<Supplier>(Supplier.class, "Phone");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Fax</b></p>
     * 
     * @return
     *     The fax contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("Fax")
    private java.lang.String fax;
    public final static SimpleProperty.String<Supplier> FAX = new SimpleProperty.String<Supplier>(Supplier.class, "Fax");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>HomePage</b></p>
     * 
     * @return
     *     The homePage contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("HomePage")
    private java.lang.String homePage;
    public final static SimpleProperty.String<Supplier> HOME_PAGE = new SimpleProperty.String<Supplier>(Supplier.class, "HomePage");
    /**
     * Navigation property <b>Products</b> for <b>Supplier</b> to multiple <b>Product</b>.
     * 
     */
    @ElementName("Products")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private List<Product> toProducts;
    /**
     * Use with available request builders to apply the <b>Products</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<Supplier, Product> TO_PRODUCTS = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<Supplier, Product>(Supplier.class, "Products", Product.class);

    @Nonnull
    @Override
    public Class<Supplier> getType() {
        return Supplier.class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>SupplierID</b></p>
     * 
     * @param supplierID
     *     The supplierID to set.
     */
    public void setSupplierID(
        @Nullable
        final Integer supplierID) {
        rememberChangedField("SupplierID", this.supplierID);
        this.supplierID = supplierID;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>CompanyName</b></p>
     * 
     * @param companyName
     *     The companyName to set.
     */
    public void setCompanyName(
        @Nullable
        final java.lang.String companyName) {
        rememberChangedField("CompanyName", this.companyName);
        this.companyName = companyName;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ContactName</b></p>
     * 
     * @param contactName
     *     The contactName to set.
     */
    public void setContactName(
        @Nullable
        final java.lang.String contactName) {
        rememberChangedField("ContactName", this.contactName);
        this.contactName = contactName;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>ContactTitle</b></p>
     * 
     * @param contactTitle
     *     The contactTitle to set.
     */
    public void setContactTitle(
        @Nullable
        final java.lang.String contactTitle) {
        rememberChangedField("ContactTitle", this.contactTitle);
        this.contactTitle = contactTitle;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Address</b></p>
     * 
     * @param address
     *     The address to set.
     */
    public void setAddress(
        @Nullable
        final java.lang.String address) {
        rememberChangedField("Address", this.address);
        this.address = address;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>City</b></p>
     * 
     * @param city
     *     The city to set.
     */
    public void setCity(
        @Nullable
        final java.lang.String city) {
        rememberChangedField("City", this.city);
        this.city = city;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Region</b></p>
     * 
     * @param region
     *     The region to set.
     */
    public void setRegion(
        @Nullable
        final java.lang.String region) {
        rememberChangedField("Region", this.region);
        this.region = region;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>PostalCode</b></p>
     * 
     * @param postalCode
     *     The postalCode to set.
     */
    public void setPostalCode(
        @Nullable
        final java.lang.String postalCode) {
        rememberChangedField("PostalCode", this.postalCode);
        this.postalCode = postalCode;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Country</b></p>
     * 
     * @param country
     *     The country to set.
     */
    public void setCountry(
        @Nullable
        final java.lang.String country) {
        rememberChangedField("Country", this.country);
        this.country = country;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Phone</b></p>
     * 
     * @param phone
     *     The phone to set.
     */
    public void setPhone(
        @Nullable
        final java.lang.String phone) {
        rememberChangedField("Phone", this.phone);
        this.phone = phone;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>Fax</b></p>
     * 
     * @param fax
     *     The fax to set.
     */
    public void setFax(
        @Nullable
        final java.lang.String fax) {
        rememberChangedField("Fax", this.fax);
        this.fax = fax;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>HomePage</b></p>
     * 
     * @param homePage
     *     The homePage to set.
     */
    public void setHomePage(
        @Nullable
        final java.lang.String homePage) {
        rememberChangedField("HomePage", this.homePage);
        this.homePage = homePage;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "Suppliers";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("SupplierID", getSupplierID());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("SupplierID", getSupplierID());
        cloudSdkValues.put("CompanyName", getCompanyName());
        cloudSdkValues.put("ContactName", getContactName());
        cloudSdkValues.put("ContactTitle", getContactTitle());
        cloudSdkValues.put("Address", getAddress());
        cloudSdkValues.put("City", getCity());
        cloudSdkValues.put("Region", getRegion());
        cloudSdkValues.put("PostalCode", getPostalCode());
        cloudSdkValues.put("Country", getCountry());
        cloudSdkValues.put("Phone", getPhone());
        cloudSdkValues.put("Fax", getFax());
        cloudSdkValues.put("HomePage", getHomePage());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("SupplierID")) {
                final Object value = cloudSdkValues.remove("SupplierID");
                if ((value == null)||(!value.equals(getSupplierID()))) {
                    setSupplierID(((Integer) value));
                }
            }
            if (cloudSdkValues.containsKey("CompanyName")) {
                final Object value = cloudSdkValues.remove("CompanyName");
                if ((value == null)||(!value.equals(getCompanyName()))) {
                    setCompanyName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ContactName")) {
                final Object value = cloudSdkValues.remove("ContactName");
                if ((value == null)||(!value.equals(getContactName()))) {
                    setContactName(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("ContactTitle")) {
                final Object value = cloudSdkValues.remove("ContactTitle");
                if ((value == null)||(!value.equals(getContactTitle()))) {
                    setContactTitle(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Address")) {
                final Object value = cloudSdkValues.remove("Address");
                if ((value == null)||(!value.equals(getAddress()))) {
                    setAddress(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("City")) {
                final Object value = cloudSdkValues.remove("City");
                if ((value == null)||(!value.equals(getCity()))) {
                    setCity(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Region")) {
                final Object value = cloudSdkValues.remove("Region");
                if ((value == null)||(!value.equals(getRegion()))) {
                    setRegion(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("PostalCode")) {
                final Object value = cloudSdkValues.remove("PostalCode");
                if ((value == null)||(!value.equals(getPostalCode()))) {
                    setPostalCode(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Country")) {
                final Object value = cloudSdkValues.remove("Country");
                if ((value == null)||(!value.equals(getCountry()))) {
                    setCountry(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Phone")) {
                final Object value = cloudSdkValues.remove("Phone");
                if ((value == null)||(!value.equals(getPhone()))) {
                    setPhone(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("Fax")) {
                final Object value = cloudSdkValues.remove("Fax");
                if ((value == null)||(!value.equals(getFax()))) {
                    setFax(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("HomePage")) {
                final Object value = cloudSdkValues.remove("HomePage");
                if ((value == null)||(!value.equals(getHomePage()))) {
                    setHomePage(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
            if ((cloudSdkValues).containsKey("Products")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("Products");
                if (cloudSdkValue instanceof Iterable) {
                    if (toProducts == null) {
                        toProducts = Lists.newArrayList();
                    } else {
                        toProducts = Lists.newArrayList(toProducts);
                    }
                    int i = 0;
                    for (Object item: ((Iterable<?> ) cloudSdkValue)) {
                        if (!(item instanceof Map)) {
                            continue;
                        }
                        Product entity;
                        if (toProducts.size()>i) {
                            entity = toProducts.get(i);
                        } else {
                            entity = new Product();
                            toProducts.add(entity);
                        }
                        i = (i + 1);
                        @SuppressWarnings("unchecked")
                        final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) item);
                        entity.fromMap(inputMap);
                    }
                }
            }
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return OdataService.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfNavigationProperties() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfNavigationProperties();
        if (toProducts!= null) {
            (cloudSdkValues).put("Products", toProducts);
        }
        return cloudSdkValues;
    }

    /**
     * Retrieval of associated <b>Product</b> entities (one to many). This corresponds to the OData navigation property <b>Products</b>.
     * <p>
     * If the navigation property for an entity <b>Supplier</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>Products</b> is already loaded, the result will contain the <b>Product</b> entities. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<List<Product>> getProductsIfPresent() {
        return Option.of(toProducts);
    }

    /**
     * Overwrites the list of associated <b>Product</b> entities for the loaded navigation property <b>Products</b>.
     * <p>
     * If the navigation property <b>Products</b> of a queried <b>Supplier</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param cloudSdkValue
     *     List of <b>Product</b> entities.
     */
    public void setProducts(
        @Nonnull
        final List<Product> cloudSdkValue) {
        if (toProducts == null) {
            toProducts = Lists.newArrayList();
        }
        toProducts.clear();
        toProducts.addAll(cloudSdkValue);
    }

    /**
     * Adds elements to the list of associated <b>Product</b> entities. This corresponds to the OData navigation property <b>Products</b>.
     * <p>
     * If the navigation property <b>Products</b> of a queried <b>Supplier</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param entity
     *     Array of <b>Product</b> entities.
     */
    public void addProducts(Product... entity) {
        if (toProducts == null) {
            toProducts = Lists.newArrayList();
        }
        toProducts.addAll(Lists.newArrayList(entity));
    }


    /**
     * Helper class to allow for fluent creation of Supplier instances.
     * 
     */
    public final static class SupplierBuilder {

        private List<Product> toProducts = Lists.newArrayList();

        private Supplier.SupplierBuilder toProducts(final List<Product> cloudSdkValue) {
            toProducts.addAll(cloudSdkValue);
            return this;
        }

        /**
         * Navigation property <b>Products</b> for <b>Supplier</b> to multiple <b>Product</b>.
         * 
         * @param cloudSdkValue
         *     The Products to build this Supplier with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public Supplier.SupplierBuilder products(Product... cloudSdkValue) {
            return toProducts(Lists.newArrayList(cloudSdkValue));
        }

    }

}
