
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.16.0
 */

package sap.example.odata.generate.namespaces.odata;

import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import sap.example.odata.generate.services.OdataService;


/**
 * <p>Original entity name from the Odata EDM: <b>Territory</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class Territory
    extends VdmEntity<Territory>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "NorthwindModel.Territory";
    /**
     * Selector for all available fields of Territory.
     * 
     */
    public final static SimpleProperty<Territory> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>TerritoryID</b></p>
     * 
     * @return
     *     The territoryID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("TerritoryID")
    private java.lang.String territoryID;
    public final static SimpleProperty.String<Territory> TERRITORY_ID = new SimpleProperty.String<Territory>(Territory.class, "TerritoryID");
    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>TerritoryDescription</b></p>
     * 
     * @return
     *     The territoryDescription contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("TerritoryDescription")
    private java.lang.String territoryDescription;
    public final static SimpleProperty.String<Territory> TERRITORY_DESCRIPTION = new SimpleProperty.String<Territory>(Territory.class, "TerritoryDescription");
    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>RegionID</b></p>
     * 
     * @return
     *     The regionID contained in this {@link VdmEntity}.
     */
    @Nullable
    @ElementName("RegionID")
    private Integer regionID;
    public final static SimpleProperty.NumericInteger<Territory> REGION_ID = new SimpleProperty.NumericInteger<Territory>(Territory.class, "RegionID");
    /**
     * Navigation property <b>Region</b> for <b>Territory</b> to single <b>Region</b>.
     * 
     */
    @ElementName("Region")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private Region toRegion;
    /**
     * Navigation property <b>Employees</b> for <b>Territory</b> to multiple <b>Employee</b>.
     * 
     */
    @ElementName("Employees")
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private List<Employee> toEmployees;
    /**
     * Use with available request builders to apply the <b>Region</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<Territory, Region> TO_REGION = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<Territory, Region>(Territory.class, "Region", Region.class);
    /**
     * Use with available request builders to apply the <b>Employees</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<Territory, Employee> TO_EMPLOYEES = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Collection<Territory, Employee>(Territory.class, "Employees", Employee.class);

    @Nonnull
    @Override
    public Class<Territory> getType() {
        return Territory.class;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>TerritoryID</b></p>
     * 
     * @param territoryID
     *     The territoryID to set.
     */
    public void setTerritoryID(
        @Nullable
        final java.lang.String territoryID) {
        rememberChangedField("TerritoryID", this.territoryID);
        this.territoryID = territoryID;
    }

    /**
     * Constraints: Nullable<p>Original property name from the Odata EDM: <b>TerritoryDescription</b></p>
     * 
     * @param territoryDescription
     *     The territoryDescription to set.
     */
    public void setTerritoryDescription(
        @Nullable
        final java.lang.String territoryDescription) {
        rememberChangedField("TerritoryDescription", this.territoryDescription);
        this.territoryDescription = territoryDescription;
    }

    /**
     * Constraints: Not nullable<p>Original property name from the Odata EDM: <b>RegionID</b></p>
     * 
     * @param regionID
     *     The regionID to set.
     */
    public void setRegionID(
        @Nullable
        final Integer regionID) {
        rememberChangedField("RegionID", this.regionID);
        this.regionID = regionID;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "Territories";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("TerritoryID", getTerritoryID());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfFields();
        cloudSdkValues.put("TerritoryID", getTerritoryID());
        cloudSdkValues.put("TerritoryDescription", getTerritoryDescription());
        cloudSdkValues.put("RegionID", getRegionID());
        return cloudSdkValues;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> cloudSdkValues = Maps.newLinkedHashMap(inputValues);
        // simple properties
        {
            if (cloudSdkValues.containsKey("TerritoryID")) {
                final Object value = cloudSdkValues.remove("TerritoryID");
                if ((value == null)||(!value.equals(getTerritoryID()))) {
                    setTerritoryID(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("TerritoryDescription")) {
                final Object value = cloudSdkValues.remove("TerritoryDescription");
                if ((value == null)||(!value.equals(getTerritoryDescription()))) {
                    setTerritoryDescription(((java.lang.String) value));
                }
            }
            if (cloudSdkValues.containsKey("RegionID")) {
                final Object value = cloudSdkValues.remove("RegionID");
                if ((value == null)||(!value.equals(getRegionID()))) {
                    setRegionID(((Integer) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
            if ((cloudSdkValues).containsKey("Region")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("Region");
                if (cloudSdkValue instanceof Map) {
                    if (toRegion == null) {
                        toRegion = new Region();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) cloudSdkValue);
                    toRegion.fromMap(inputMap);
                }
            }
            if ((cloudSdkValues).containsKey("Employees")) {
                final Object cloudSdkValue = (cloudSdkValues).remove("Employees");
                if (cloudSdkValue instanceof Iterable) {
                    if (toEmployees == null) {
                        toEmployees = Lists.newArrayList();
                    } else {
                        toEmployees = Lists.newArrayList(toEmployees);
                    }
                    int i = 0;
                    for (Object item: ((Iterable<?> ) cloudSdkValue)) {
                        if (!(item instanceof Map)) {
                            continue;
                        }
                        Employee entity;
                        if (toEmployees.size()>i) {
                            entity = toEmployees.get(i);
                        } else {
                            entity = new Employee();
                            toEmployees.add(entity);
                        }
                        i = (i + 1);
                        @SuppressWarnings("unchecked")
                        final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) item);
                        entity.fromMap(inputMap);
                    }
                }
            }
        }
        super.fromMap(cloudSdkValues);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return OdataService.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfNavigationProperties() {
        final Map<java.lang.String, Object> cloudSdkValues = super.toMapOfNavigationProperties();
        if (toRegion!= null) {
            (cloudSdkValues).put("Region", toRegion);
        }
        if (toEmployees!= null) {
            (cloudSdkValues).put("Employees", toEmployees);
        }
        return cloudSdkValues;
    }

    /**
     * Retrieval of associated <b>Region</b> entity (one to one). This corresponds to the OData navigation property <b>Region</b>.
     * <p>
     * If the navigation property for an entity <b>Territory</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>Region</b> is already loaded, the result will contain the <b>Region</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<Region> getRegionIfPresent() {
        return Option.of(toRegion);
    }

    /**
     * Overwrites the associated <b>Region</b> entity for the loaded navigation property <b>Region</b>.
     * 
     * @param cloudSdkValue
     *     New <b>Region</b> entity.
     */
    public void setRegion(final Region cloudSdkValue) {
        toRegion = cloudSdkValue;
    }

    /**
     * Retrieval of associated <b>Employee</b> entities (one to many). This corresponds to the OData navigation property <b>Employees</b>.
     * <p>
     * If the navigation property for an entity <b>Territory</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>Employees</b> is already loaded, the result will contain the <b>Employee</b> entities. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<List<Employee>> getEmployeesIfPresent() {
        return Option.of(toEmployees);
    }

    /**
     * Overwrites the list of associated <b>Employee</b> entities for the loaded navigation property <b>Employees</b>.
     * <p>
     * If the navigation property <b>Employees</b> of a queried <b>Territory</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param cloudSdkValue
     *     List of <b>Employee</b> entities.
     */
    public void setEmployees(
        @Nonnull
        final List<Employee> cloudSdkValue) {
        if (toEmployees == null) {
            toEmployees = Lists.newArrayList();
        }
        toEmployees.clear();
        toEmployees.addAll(cloudSdkValue);
    }

    /**
     * Adds elements to the list of associated <b>Employee</b> entities. This corresponds to the OData navigation property <b>Employees</b>.
     * <p>
     * If the navigation property <b>Employees</b> of a queried <b>Territory</b> is operated lazily, an <b>ODataException</b> can be thrown in case of an OData query error.
     * <p>
     * Please note: <i>Lazy</i> loading of OData entity associations is the process of asynchronous retrieval and persisting of items from a navigation property. If a <i>lazy</i> property is requested by the application for the first time and it has not yet been loaded, an OData query will be run in order to load the missing information and its result will get cached for future invocations.
     * 
     * @param entity
     *     Array of <b>Employee</b> entities.
     */
    public void addEmployees(Employee... entity) {
        if (toEmployees == null) {
            toEmployees = Lists.newArrayList();
        }
        toEmployees.addAll(Lists.newArrayList(entity));
    }


    /**
     * Helper class to allow for fluent creation of Territory instances.
     * 
     */
    public final static class TerritoryBuilder {

        private Region toRegion;
        private List<Employee> toEmployees = Lists.newArrayList();

        private Territory.TerritoryBuilder toRegion(final Region cloudSdkValue) {
            toRegion = cloudSdkValue;
            return this;
        }

        /**
         * Navigation property <b>Region</b> for <b>Territory</b> to single <b>Region</b>.
         * 
         * @param cloudSdkValue
         *     The Region to build this Territory with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public Territory.TerritoryBuilder region(final Region cloudSdkValue) {
            return toRegion(cloudSdkValue);
        }

        private Territory.TerritoryBuilder toEmployees(final List<Employee> cloudSdkValue) {
            toEmployees.addAll(cloudSdkValue);
            return this;
        }

        /**
         * Navigation property <b>Employees</b> for <b>Territory</b> to multiple <b>Employee</b>.
         * 
         * @param cloudSdkValue
         *     The Employees to build this Territory with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public Territory.TerritoryBuilder employees(Employee... cloudSdkValue) {
            return toEmployees(Lists.newArrayList(cloudSdkValue));
        }

    }

}
