---
spring:
  config.activate.on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  h2:
    console:
      enabled: true

---
custom:
  datasource:
    hostname: ${vcap.services.postgre-db.credentials.hostname}
    port: ${vcap.services.postgre-db.credentials.port}
    dbname: ${vcap.services.postgre-db.credentials.dbname}

spring:
  config.activate.on-profile: cloud
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${vcap.services.postgre-db.credentials.username}
    password: ${vcap.services.postgre-db.credentials.password}
    url: jdbc:postgresql://${custom.datasource.hostname}:${custom.datasource.port}/${custom.datasource.dbname}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect